### PR TITLE
Add course groups to Export and display group filter on first, 'My Appointments' tab

### PR DESCRIPTION
**Pull request by 5882wolverine**
As per the two issues here; https://github.com/5882wolverine/moodle-mod_scheduler/issues?q=is%3Aissue+is%3Aclosed

These enhancements revolve around course group information.  

**Export the course groups in individual columns in the Export tab**

For modules that use a large number of groups, it will be useful from the data analytics perspective, to view attendance data for courses that are not necessarily monitored (as some of the students).  It will also be useful to monitor Tier 4 International students.  These students have sponsored International Visas, which require some sort of evidence to the authorities that they are actually attending their course.

**Show the "Visible groups" filter on the first, "My Appointments" tab.**

This will avoid confusion so that users are aware that a group filter is active and what it is currently set to. For example, if they have selected a specific group filter on a different tab.

Thanks!

### CODE REVIEW

**Comment by jezhops** [comment]
Hi Henning,

_Re: Export the course groups in individual columns in the Export tab_

The groups were added one per column to make it easy to filter in the csv export. If they are added as comma de-limited fields then you cannot easily filter based on membership of multiple groups.

Moving the check box under "student" would be easy enough.

I guess we could look at the grouping behaviour if it would make a difference in terms of getting these changes merged into your version?

_Re: Show the "Visible groups" filter on the first, "My Appointments" tab._

Changing the group filter does have an effect on the "My Appointments" tab which caused us a major usability issue. When the group filter in the other tab is changed a teacher can completely use sight of their own slots and there is noting to indicate why. This caused us a lot of problems and actually took us a while to figure out what was going on.

The following screen recording illustrates the problem we had:

https://livecoventryac-my.sharepoint.com/:v:/g/personal/ac1216_coventry_ac_uk/EXR5Qy8WDH5DobNlh6uh-1gBmBFRuaHS8tGp3_ohAv3YTA?e=zuVs24

**Comment by bostelm** [comment]
Hello Jez,
Sorry for not getting back to you earlier. I think there are two issues here which we should separate.

(a) Exporting group information (as an additional feature). I think this is useful and I'm planning to integrate it. However, thinking about it, I'd prefer a different implementation. I have added a branch "groupexport" on my github repository, which I think adds the required features. Comment appreciated; I'm planning to add this for the 3.5 release.

(b) The behaviour with group filters in the "My Appointments" tab. It appears that you've found some kind of bug, however I'm still not quite sure about the details. Unfortunately the link that you posted is no longer valid. Could you post it again?

Thanks
Henning

**Comment by jezhops** [comment]
Hi Henning,

Thanks for your reply, we will take a look at your branch.

I just sent another link for the screen recording to you via messages on Moodle.Org

Jeremy

**Comment by bostelm** [comment]
Hi Jez,
thanks. Yes, this is in fact a bug. I'm tracking it as [CONTRIB-7277](https://tracker.moodle.org/browse/CONTRIB-7277) (ust for the record) but should hopefully fix it soon.

**Comment by bostelm** [comment]
The group information export has been implemented in Scheduler quite a while ago now, and is part of Scheduler 3.5.x. I think I just forgot to close this pull request.

**Pull request closed without merging**
