### PR TITLE
Added support for block_myoverview in Moodle 3.3+

### PR DESCRIPTION
**Pull request by ndunand**
cf. https://docs.moodle.org/dev/Calendar_API#Action_events

According to Moodle 3.3 documentation, the new Course Overview block displays notifications in My Page when a teacher sets an 'Expect completed on' date in the activity completion settings. This works will core modules and should work consistently with 3rd-party modules as well.

see https://docs.moodle.org/33/en/Course_overview 

The proposed changes would implement this in mod_scheduler

### CODE REVIEW

**Comment by bostelm** [comment]
Hello
Thanks for your contribution. I'm considering this for integration for the Scheduler 3.5 release in a few months' time. However, the slightly weird thing is that Scheduler does not currently support activity completion. Hence solving this via the "Expect completion on " date seems slightly odd. Are you sure it works as expected?

**Comment by ndunand** [comment]
@bostelm yes, this works as expected. You can event set this "Expect completion on" on a label (maybe for some offline activity for instance)

**Comment by ndunand** [comment]
Hello,
I'm just wondering if you had thought about merging this.

**Comment by bostelm** [comment]
I've merged this into master now. Thanks for your contribution, and apologies for the long delay.

**Comment by ndunand** [comment]
Thanks 😊

**Pull request merged**
